import { ToolDefinition } from "@/domain/types";

export const tools: ToolDefinition[] = [
  {
    id: "json-formatter",
    name: "JSON Formatter",
    description: "JSON整形・圧縮・バリデーション",
    category: "Formatter",
    icon: "{ }",
    implemented: true,
  },
  {
    id: "base64",
    name: "Base64",
    description: "Base64エンコード/デコード",
    category: "Encoder",
    icon: "B64",
    implemented: true,
  },
  {
    id: "url-encode",
    name: "URL Encode",
    description: "URLエンコード/デコード",
    category: "Encoder",
    icon: "%20",
    implemented: true,
  },
  {
    id: "regex-tester",
    name: "Regex Tester",
    description: "正規表現テスター",
    category: "Tester",
    icon: ".*",
    implemented: true,
  },
  {
    id: "diff-checker",
    name: "Diff Checker",
    description: "テキスト差分比較",
    category: "Comparator",
    icon: "+-",
    implemented: true,
  },
  {
    id: "markdown-preview",
    name: "Markdown Preview",
    description: "Markdownプレビュー",
    category: "Preview",
    icon: "MD",
    implemented: true,
  },
  {
    id: "json-path",
    name: "JSONPath",
    description: "JSONPath検索",
    category: "Query",
    icon: "$..",
    implemented: true,
  },
  {
    id: "hash-generator",
    name: "Hash Generator",
    description: "ハッシュ生成（SHA-256等）",
    category: "Crypto",
    icon: "#",
    implemented: true,
  },
  {
    id: "password-generator",
    name: "Password Generator",
    description: "パスワード生成",
    category: "Crypto",
    icon: "***",
    implemented: true,
  },
  {
    id: "color-converter",
    name: "Color Converter",
    description: "HEX/RGB/HSL変換",
    category: "Converter",
    icon: "CLR",
    implemented: true,
  },
  {
    id: "timestamp-converter",
    name: "Timestamp Converter",
    description: "Unix Timestamp変換",
    category: "Converter",
    icon: "TS",
    implemented: true,
  },
  {
    id: "uuid-generator",
    name: "UUID Generator",
    description: "UUID生成",
    category: "Generator",
    icon: "ID",
    implemented: true,
  },
  {
    id: "jwt-decoder",
    name: "JWT Decoder",
    description: "JWTトークンデコード",
    category: "Decoder",
    icon: "JWT",
    implemented: true,
  },
  {
    id: "html-entity",
    name: "HTML Entity",
    description: "HTMLエンティティ変換",
    category: "Encoder",
    icon: "&;",
    implemented: true,
  },
  {
    id: "cron-parser",
    name: "Cron Parser",
    description: "Cron式パーサー",
    category: "Parser",
    icon: "CRN",
    implemented: true,
  },
  {
    id: "ip-calc",
    name: "IP Calculator",
    description: "IPアドレス・サブネット計算",
    category: "Calculator",
    icon: "IP",
    implemented: true,
  },
  {
    id: "gradient",
    name: "CSS Gradient",
    description: "CSSグラデーション生成",
    category: "Generator",
    icon: "GRD",
    implemented: true,
  },
  {
    id: "chmod",
    name: "chmod Calculator",
    description: "chmodパーミッション計算",
    category: "Calculator",
    icon: "755",
    implemented: true,
  },
  {
    id: "csv-json",
    name: "CSV ⇔ JSON",
    description: "CSV/JSON相互変換",
    category: "Converter",
    icon: "CSV",
    implemented: true,
  },
  {
    id: "sql-formatter",
    name: "SQL Formatter",
    description: "SQLフォーマッター",
    category: "Formatter",
    icon: "SQL",
    implemented: true,
  },
  {
    id: "byte-converter",
    name: "Byte Converter",
    description: "バイト単位変換",
    category: "Converter",
    icon: "B",
    implemented: true,
  },
  {
    id: "http-status",
    name: "HTTP Status",
    description: "HTTPステータスコード一覧",
    category: "Reference",
    icon: "200",
    implemented: true,
  },
  {
    id: "lorem",
    name: "Lorem Ipsum",
    description: "Lorem Ipsumダミーテキスト生成",
    category: "Generator",
    icon: "TXT",
    implemented: true,
  },
  {
    id: "qr-generator",
    name: "QR Generator",
    description: "QRコード生成",
    category: "Generator",
    icon: "QR",
    implemented: true,
  },
  {
    id: "base-converter",
    name: "Base Converter",
    description: "進数変換（2/8/10/16進数）",
    category: "Converter",
    icon: "0x",
    implemented: true,
  },
  {
    id: "yaml-formatter",
    name: "YAML Formatter",
    description: "YAML整形・バリデーション・JSON変換",
    category: "Formatter",
    icon: "YML",
    implemented: true,
  },
  {
    id: "text-case",
    name: "Text Case Converter",
    description: "テキストケース変換（camel/snake/kebab等）",
    category: "Converter",
    icon: "Aa",
    implemented: true,
  },
  {
    id: "url-parser",
    name: "URL Parser",
    description: "URL解析・各要素の分解と再構築",
    category: "Parser",
    icon: "URL",
    implemented: true,
  },
  {
    id: "json-to-ts",
    name: "JSON → TypeScript",
    description: "JSONからTypeScript型定義を生成",
    category: "Generator",
    icon: "TS",
    implemented: true,
  },
  {
    id: "string-escape",
    name: "String Escape",
    description: "文字列エスケープ・アンエスケープ",
    category: "Encoder",
    icon: "\\n",
    implemented: true,
  },
  {
    id: "css-minifier",
    name: "CSS Minifier",
    description: "CSS圧縮・整形",
    category: "Formatter",
    icon: "CSS",
    implemented: true,
  },
  {
    id: "html-formatter",
    name: "HTML Formatter",
    description: "HTML整形・圧縮",
    category: "Formatter",
    icon: "</>",
    implemented: true,
  },
  {
    id: "ascii-table",
    name: "ASCII Table",
    description: "ASCIIコード表（検索・フィルター付き）",
    category: "Reference",
    icon: "ASC",
    implemented: true,
  },
  {
    id: "crontab-generator",
    name: "Crontab Generator",
    description: "Cron式ビジュアル生成・次回実行表示",
    category: "Generator",
    icon: "⏰",
    implemented: true,
  },
  {
    id: "jwt-generator",
    name: "JWT Generator",
    description: "JWTトークン生成（HS256）",
    category: "Crypto",
    icon: "JWT",
    implemented: true,
  },
  {
    id: "meta-tag",
    name: "Meta Tag / OGP",
    description: "メタタグ・OGPプレビュー生成",
    category: "Generator",
    icon: "OG",
    implemented: true,
  },
  {
    id: "gitignore-generator",
    name: ".gitignore Generator",
    description: "言語・フレームワーク別.gitignore生成",
    category: "Generator",
    icon: ".gi",
    implemented: true,
  },
  {
    id: "markdown-table",
    name: "Markdown Table",
    description: "GUIでMarkdownテーブル生成",
    category: "Generator",
    icon: "TBL",
    implemented: true,
  },
  {
    id: "placeholder-image",
    name: "Placeholder Image",
    description: "SVGプレースホルダー画像生成",
    category: "Generator",
    icon: "IMG",
    implemented: true,
  },
  {
    id: "regex-builder",
    name: "Regex Builder",
    description: "ビジュアル正規表現ビルダー",
    category: "Generator",
    icon: "RE",
    implemented: true,
  },
  {
    id: "svg-viewer",
    name: "SVG Viewer",
    description: "SVG表示・最適化・サイズ分析",
    category: "Preview",
    icon: "SVG",
    implemented: true,
  },
  {
    id: "color-palette",
    name: "Color Palette",
    description: "ベースカラーから配色パレット自動生成",
    category: "Generator",
    icon: "CLR",
    implemented: true,
  },
  {
    id: "robots-txt",
    name: "robots.txt Generator",
    description: "robots.txtファイル生成",
    category: "Generator",
    icon: "BOT",
    implemented: true,
  },
  {
    id: "nginx-config",
    name: "Nginx Config",
    description: "Nginxサーバー設定生成",
    category: "Generator",
    icon: "NGX",
    implemented: true,
  },
  {
    id: "docker-compose",
    name: "Docker Compose",
    description: "docker runコマンドをCompose形式に変換",
    category: "Converter",
    icon: "DCK",
    implemented: true,
  },
  {
    id: "favicon-generator",
    name: "Favicon Generator",
    description: "絵文字・文字からSVG Favicon生成",
    category: "Generator",
    icon: "FAV",
    implemented: true,
  },
  {
    id: "unicode-lookup",
    name: "Unicode Lookup",
    description: "Unicode文字検索・コードポイント表示",
    category: "Reference",
    icon: "U+",
    implemented: true,
  },
  // --- Batch 1: Encoder/Converter ---
  {
    id: "hex-encoder",
    name: "Hex Encoder",
    description: "16進数エンコード/デコード",
    category: "Encoder",
    icon: "0xF",
    implemented: true,
  },
  {
    id: "rot13",
    name: "ROT13",
    description: "ROT13暗号化/復号化",
    category: "Encoder",
    icon: "R13",
    implemented: true,
  },
  {
    id: "morse-code",
    name: "Morse Code",
    description: "モールス信号変換",
    category: "Encoder",
    icon: "·−",
    implemented: true,
  },
  {
    id: "toml-converter",
    name: "TOML Converter",
    description: "TOML ⇔ JSON変換",
    category: "Converter",
    icon: "TML",
    implemented: true,
  },
  {
    id: "number-formatter",
    name: "Number Formatter",
    description: "数値フォーマット（桁区切り・通貨・科学表記）",
    category: "Formatter",
    icon: "1,0",
    implemented: true,
  },
  {
    id: "css-unit-converter",
    name: "CSS Unit Converter",
    description: "CSS単位変換（px/rem/em/vw/vh）",
    category: "Converter",
    icon: "rem",
    implemented: true,
  },
  {
    id: "xml-json",
    name: "XML ⇔ JSON",
    description: "XML/JSON相互変換",
    category: "Converter",
    icon: "XML",
    implemented: true,
  },
  {
    id: "markdown-html",
    name: "Markdown → HTML",
    description: "MarkdownをHTMLに変換",
    category: "Converter",
    icon: "M→H",
    implemented: true,
  },
  // --- Batch 2: Formatter/Generator ---
  {
    id: "js-formatter",
    name: "JS Formatter",
    description: "JavaScript/TypeScript整形・圧縮",
    category: "Formatter",
    icon: "JS",
    implemented: true,
  },
  {
    id: "xml-formatter",
    name: "XML Formatter",
    description: "XML整形・圧縮・バリデーション",
    category: "Formatter",
    icon: "XML",
    implemented: true,
  },
  {
    id: "slug-generator",
    name: "Slug Generator",
    description: "URLスラッグ生成",
    category: "Generator",
    icon: "/-/",
    implemented: true,
  },
  {
    id: "data-url",
    name: "Data URL",
    description: "Data URL生成（テキスト・SVG対応）",
    category: "Generator",
    icon: "D:U",
    implemented: true,
  },
  {
    id: "box-shadow",
    name: "Box Shadow",
    description: "CSS box-shadowビジュアル生成",
    category: "Generator",
    icon: "SHD",
    implemented: true,
  },
  {
    id: "border-radius",
    name: "Border Radius",
    description: "CSS border-radiusビジュアル生成",
    category: "Generator",
    icon: "◜◝",
    implemented: true,
  },
  {
    id: "flexbox-generator",
    name: "Flexbox Generator",
    description: "CSS Flexboxプレイグラウンド",
    category: "Generator",
    icon: "FLX",
    implemented: true,
  },
  {
    id: "grid-generator",
    name: "Grid Generator",
    description: "CSS Gridレイアウト生成",
    category: "Generator",
    icon: "GRD",
    implemented: true,
  },
  // --- Batch 3: Analyzer/Tester ---
  {
    id: "text-counter",
    name: "Text Counter",
    description: "テキスト統計（文字数・単語数・読了時間）",
    category: "Analyzer",
    icon: "WC",
    implemented: true,
  },
  {
    id: "json-size",
    name: "JSON Size",
    description: "JSONサイズ・構造分析",
    category: "Analyzer",
    icon: "JSz",
    implemented: true,
  },
  {
    id: "date-calculator",
    name: "Date Calculator",
    description: "日付計算（差分・加算・減算）",
    category: "Calculator",
    icon: "CAL",
    implemented: true,
  },
  {
    id: "aspect-ratio",
    name: "Aspect Ratio",
    description: "アスペクト比計算",
    category: "Calculator",
    icon: "16:9",
    implemented: true,
  },
  {
    id: "color-contrast",
    name: "Color Contrast",
    description: "WCAGコントラスト比チェッカー",
    category: "Tester",
    icon: "AA",
    implemented: true,
  },
  {
    id: "emoji-picker",
    name: "Emoji Picker",
    description: "絵文字検索・コピー",
    category: "Reference",
    icon: "😀",
    implemented: true,
  },
  {
    id: "json-validator",
    name: "JSON Validator",
    description: "JSONバリデーション（エラー行列表示）",
    category: "Tester",
    icon: "✓J",
    implemented: true,
  },
  {
    id: "semver-tester",
    name: "Semver Tester",
    description: "セマンティックバージョニングテスター",
    category: "Tester",
    icon: "1.0",
    implemented: true,
  },
  // --- Batch 4: Reference/Generator ---
  {
    id: "html-colors",
    name: "HTML Colors",
    description: "HTML/CSSカラーネーム一覧",
    category: "Reference",
    icon: "🎨",
    implemented: true,
  },
  {
    id: "mime-types",
    name: "MIME Types",
    description: "MIMEタイプ一覧（拡張子検索）",
    category: "Reference",
    icon: "MIM",
    implemented: true,
  },
  {
    id: "keyboard-codes",
    name: "Keyboard Codes",
    description: "キーボードイベントコード表示",
    category: "Reference",
    icon: "⌨️",
    implemented: true,
  },
  {
    id: "css-specificity",
    name: "CSS Specificity",
    description: "CSSセレクター詳細度計算",
    category: "Calculator",
    icon: "CSS",
    implemented: true,
  },
  {
    id: "email-validator",
    name: "Email Validator",
    description: "メールアドレスバリデーション",
    category: "Tester",
    icon: "@",
    implemented: true,
  },
  {
    id: "htaccess-generator",
    name: ".htaccess Generator",
    description: ".htaccessファイル生成",
    category: "Generator",
    icon: ".ht",
    implemented: true,
  },
  {
    id: "editorconfig",
    name: "EditorConfig",
    description: "EditorConfig生成",
    category: "Generator",
    icon: "EC",
    implemented: true,
  },
  {
    id: "tsconfig",
    name: "tsconfig.json",
    description: "tsconfig.json生成",
    category: "Generator",
    icon: "TSc",
    implemented: true,
  },
  // --- Batch 5: Advanced ---
  {
    id: "nanoid",
    name: "NanoID Generator",
    description: "NanoID/ランダムID生成",
    category: "Generator",
    icon: "NID",
    implemented: true,
  },
  {
    id: "punycode",
    name: "Punycode",
    description: "Punycodeエンコード/デコード（国際ドメイン名）",
    category: "Encoder",
    icon: "xn-",
    implemented: true,
  },
  {
    id: "sql-generator",
    name: "SQL Generator",
    description: "SQL文生成（CREATE/INSERT/ALTER）",
    category: "Generator",
    icon: "SQL",
    implemented: true,
  },
  {
    id: "eslint-config",
    name: "ESLint Config",
    description: "ESLint設定ファイル生成",
    category: "Generator",
    icon: "ESL",
    implemented: true,
  },
  {
    id: "text-diff-inline",
    name: "Inline Diff",
    description: "インラインテキスト差分表示",
    category: "Comparator",
    icon: "±",
    implemented: true,
  },
  {
    id: "json-to-go",
    name: "JSON → Go",
    description: "JSONからGo構造体生成",
    category: "Generator",
    icon: "Go",
    implemented: true,
  },
  {
    id: "json-to-python",
    name: "JSON → Python",
    description: "JSONからPython dataclass生成",
    category: "Generator",
    icon: "Py",
    implemented: true,
  },
  {
    id: "base58",
    name: "Base58",
    description: "Base58エンコード/デコード（Bitcoin形式）",
    category: "Encoder",
    icon: "B58",
    implemented: true,
  },
];

export function getToolById(id: string): ToolDefinition | undefined {
  return tools.find((t) => t.id === id);
}

export function getImplementedTools(): ToolDefinition[] {
  return tools.filter((t) => t.implemented);
}
