import { ToolDefinition } from "@/domain/types";

export const tools: ToolDefinition[] = [
  {
    id: "json-formatter",
    name: "JSON Formatter",
    description: "JSON整形・圧縮・バリデーション",
    category: "Formatter",
    icon: "{ }",
    implemented: true,
  },
  {
    id: "base64",
    name: "Base64",
    description: "Base64エンコード/デコード",
    category: "Encoder",
    icon: "B64",
    implemented: true,
  },
  {
    id: "url-encode",
    name: "URL Encode",
    description: "URLエンコード/デコード",
    category: "Encoder",
    icon: "%20",
    implemented: true,
  },
  {
    id: "regex-tester",
    name: "Regex Tester",
    description: "正規表現テスター",
    category: "Tester",
    icon: ".*",
    implemented: true,
  },
  {
    id: "diff-checker",
    name: "Diff Checker",
    description: "テキスト差分比較",
    category: "Comparator",
    icon: "+-",
    implemented: true,
  },
  {
    id: "markdown-preview",
    name: "Markdown Preview",
    description: "Markdownプレビュー",
    category: "Preview",
    icon: "MD",
    implemented: true,
  },
  {
    id: "json-path",
    name: "JSONPath",
    description: "JSONPath検索",
    category: "Query",
    icon: "$..",
    implemented: true,
  },
  {
    id: "hash-generator",
    name: "Hash Generator",
    description: "ハッシュ生成（SHA-256等）",
    category: "Crypto",
    icon: "#",
    implemented: true,
  },
  {
    id: "password-generator",
    name: "Password Generator",
    description: "パスワード生成",
    category: "Crypto",
    icon: "***",
    implemented: true,
  },
  {
    id: "color-converter",
    name: "Color Converter",
    description: "HEX/RGB/HSL変換",
    category: "Converter",
    icon: "CLR",
    implemented: true,
  },
  {
    id: "timestamp-converter",
    name: "Timestamp Converter",
    description: "Unix Timestamp変換",
    category: "Converter",
    icon: "TS",
    implemented: true,
  },
  {
    id: "uuid-generator",
    name: "UUID Generator",
    description: "UUID生成",
    category: "Generator",
    icon: "ID",
    implemented: true,
  },
  {
    id: "jwt-decoder",
    name: "JWT Decoder",
    description: "JWTトークンデコード",
    category: "Decoder",
    icon: "JWT",
    implemented: true,
  },
  {
    id: "html-entity",
    name: "HTML Entity",
    description: "HTMLエンティティ変換",
    category: "Encoder",
    icon: "&;",
    implemented: true,
  },
  {
    id: "cron-parser",
    name: "Cron Parser",
    description: "Cron式パーサー",
    category: "Parser",
    icon: "CRN",
    implemented: true,
  },
  {
    id: "ip-calc",
    name: "IP Calculator",
    description: "IPアドレス・サブネット計算",
    category: "Calculator",
    icon: "IP",
    implemented: true,
  },
  {
    id: "gradient",
    name: "CSS Gradient",
    description: "CSSグラデーション生成",
    category: "Generator",
    icon: "GRD",
    implemented: true,
  },
  {
    id: "chmod",
    name: "chmod Calculator",
    description: "chmodパーミッション計算",
    category: "Calculator",
    icon: "755",
    implemented: true,
  },
  {
    id: "csv-json",
    name: "CSV ⇔ JSON",
    description: "CSV/JSON相互変換",
    category: "Converter",
    icon: "CSV",
    implemented: true,
  },
  {
    id: "sql-formatter",
    name: "SQL Formatter",
    description: "SQLフォーマッター",
    category: "Formatter",
    icon: "SQL",
    implemented: true,
  },
  {
    id: "byte-converter",
    name: "Byte Converter",
    description: "バイト単位変換",
    category: "Converter",
    icon: "B",
    implemented: true,
  },
  {
    id: "http-status",
    name: "HTTP Status",
    description: "HTTPステータスコード一覧",
    category: "Reference",
    icon: "200",
    implemented: true,
  },
  {
    id: "lorem",
    name: "Lorem Ipsum",
    description: "Lorem Ipsumダミーテキスト生成",
    category: "Generator",
    icon: "TXT",
    implemented: true,
  },
  {
    id: "qr-generator",
    name: "QR Generator",
    description: "QRコード生成",
    category: "Generator",
    icon: "QR",
    implemented: true,
  },
  {
    id: "base-converter",
    name: "Base Converter",
    description: "進数変換（2/8/10/16進数）",
    category: "Converter",
    icon: "0x",
    implemented: true,
  },
];

export function getToolById(id: string): ToolDefinition | undefined {
  return tools.find((t) => t.id === id);
}

export function getImplementedTools(): ToolDefinition[] {
  return tools.filter((t) => t.implemented);
}
